# Generated by Django 3.1.1 on 2021-01-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210130_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='post',
        ),
    ]
