# Generated by Django 3.1.1 on 2020-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201128_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.related.OneToOneField>/cover_image'),
        ),
    ]
