# Generated by Django 3.1.1 on 2021-01-16 09:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210116_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=user.models.upload_cover_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defaults/profile_pic.jpg', null=True, upload_to=user.models.upload_profile_to),
        ),
    ]
